### PR TITLE
improve spelling & #739

### PR DESCRIPTION
**Pull request by eurobots**
Hello,

there are two spelling errors which I've fixed.

With best regards,

Udo

### CODE REVIEW

**Comment by dwrolvink** [comment]
Hi Udo, thanks for your PR!
Unfortunately, since you've used your master branch for this PR, the subsequent pushes have also been added. I don't think you meant to send these along in this PR.

I can apply these changes by hand and close this PR, I think that is easiest. In the future you could avoid this by creating a new branch with the changes you want to send, and then continue in your master branch.

**Comment by eurobots** [comment]
Hello,

I was just proposing to add those subsequent pushes as well :)

They work on Issue #739.

More commits may be expected.

With best regards

Udo

**Comment by dwrolvink** [comment]
Ahh in that case.

Let me know when you are done with this issue, then I can merge it. 
(If you add too many different things in one PR, I might not want to pull on one thing, where all the others are nice, and that can be a headache)

Thanks for contributing!

**Comment by dwrolvink** [comment]
Some feedback already:
`cl_toggle` is used by many different divs, you've now added `setContentHeight` which sets the container height. 
Maybe you'd want to add this only to `toggle_menu`? (I don't think toggling callouts to open/close should impact the container height?).

Instead of `onload="onInitial()"` in the body, you could move your function to just above this line:
https://github.com/obsidian-html/obsidian-html/blob/70572d7a1364e087f963cff1b2fc257a9b880cae/obsidianhtml/src/js/obsidian_core.js#L150

And then call your function in the top of the load_page function. That way, there is one clear function that is run right after page load, keeps everything a bit more tidy. (Unless you have a good reason to have this separate).

**Comment by dwrolvink** [comment]
Closing as no feedback is given and I don't like pull requests staying open for too long.
Once you are done you can create a new PR.

**Pull request closed without merging**
